version: 0.2

phases:
  pre_build:
    commands:
      - 'echo "=== Pre-Build ==="'
      # 1) .git 없어도 찍히는 SHA/시간
      - 'echo "Resolved SHA (full): $CODEBUILD_RESOLVED_SOURCE_VERSION"'
      - 'echo "Resolved SHA (short): ${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}"'

  install:
    commands:
      - echo "=== Install ==="
      - cd frontend
      - npm i

  build:
    commands:
      - echo "=== Build ==="
      - npm run build

  post_build:
    commands:
      - echo "=== Post-Build ==="
      - ls -al dist

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
