version: 0.2

env:
  variables:
    # 선택: 커밋 메시지까지 찍고 싶으면 CodeBuild 환경변수에 GIT_REMOTE_URL을 세팅해줘
    # 예) https://github.com/woowacourse-teams/2025-estime.git
    GIT_REMOTE_URL: 'https://github.com/woowacourse-teams/2025-estime.git'

phases:
  pre_build:
    commands:
      - echo "=== Pre-Build ==="
      # 1) .git 없어도 항상 나오는 CodeBuild 기본 변수 (현재 커밋 SHA)
      - echo "Resolved SHA: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Build time: $(date '+%Y-%m-%d %H:%M:%S%z')"

      # 2) (옵션) 커밋 메시지까지 보고 싶을 때: 얕은 fetch로 .git 메타만 주입
      - |
        if [ -n "$GIT_REMOTE_URL" ]; then
          echo "[git meta] injecting .git into frontend/"
          cd "$CODEBUILD_SRC_DIR/frontend"
          git init
          git remote add origin "$GIT_REMOTE_URL"
          git fetch --depth=1 --filter=blob:none origin "$CODEBUILD_RESOLVED_SOURCE_VERSION"
          git update-ref HEAD "$CODEBUILD_RESOLVED_SOURCE_VERSION"
          echo "Commit short : $(git rev-parse --short HEAD)"
          echo "Commit message: $(git log -1 --pretty=%s)"
          cd "$CODEBUILD_SRC_DIR"
        else
          echo "[git meta] GIT_REMOTE_URL not set -> skip git log"
        fi

  install:
    commands:
      - echo "=== Install ==="
      - cd frontend
      - npm i

  build:
    commands:
      - echo "=== Build ==="
      - npm run build

  post_build:
    commands:
      - echo "=== Post-Build ==="
      - ls -al dist

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
