version: 0.2

env:
  exported-variables:
    - COMMIT_HASH

cache:
  paths:
    - 'frontend/node_modules/**/*'
    - '/root/.local/share/pnpm/store/**/*'
    - '/root/.npm/_cacache/**/*' # pnpm 캐싱
    - 'frontend/node_modules/.cache/**/*'

phases:
  pre_build:
    commands:
      - echo "=== Pre-Build ==="
      - export COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - 'echo "Resolved SHA (short): ${COMMIT_HASH}"'

  install:
    commands:
      - echo "=== Install Dependencies ==="
      - cd frontend
      - npm install -g pnpm
      - pnpm install --frozen-lockfile

  build:
    commands:
      - echo "=== Build Project ==="
      - pnpm run build

  post_build:
    commands:
      - echo "=== Post-Build ==="
      - ls -al dist

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
