version: 0.2

env:
  variables:
    # 선택: 커밋 메시지까지 찍고 싶으면 CodeBuild 환경변수에 GIT_REMOTE_URL을 세팅해줘
    # 예) https://github.com/woowacourse-teams/2025-estime.git
    GIT_REMOTE_URL: 'https://github.com/woowacourse-teams/2025-estime.git'

phases:
  pre_build:
    commands:
      - echo "=== Pre-Build ==="
      # 1) .git 없어도 찍힘
      - echo "Resolved SHA (full): $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Resolved SHA (short): ${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}"
      - echo "Build time: $(date '+%Y-%m-%d %H:%M:%S%z')"

      # 2) (옵션) 커밋 메시지까지 보고 싶을 때: .git 메타만 주입해서 로그로 출력
      - test -n "$GIT_REMOTE_URL" || echo "[git meta] GIT_REMOTE_URL not set -> skip git log"
      - test -z "$GIT_REMOTE_URL" || echo "[git meta] injecting .git into frontend/"
      - test -z "$GIT_REMOTE_URL" || cd "$CODEBUILD_SRC_DIR/frontend"
      - test -z "$GIT_REMOTE_URL" || git init
      - test -z "$GIT_REMOTE_URL" || git remote add origin "$GIT_REMOTE_URL"
      - test -z "$GIT_REMOTE_URL" || git fetch --depth=1 --filter=blob:none origin "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - test -z "$GIT_REMOTE_URL" || git update-ref HEAD "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - test -z "$GIT_REMOTE_URL" || git rev-parse --short HEAD
      - test -z "$GIT_REMOTE_URL" || git log -1 --pretty="Commit msg: %s"
      - test -z "$GIT_REMOTE_URL" || cd "$CODEBUILD_SRC_DIR"

  install:
    commands:
      - echo "=== Install ==="
      - cd frontend
      - npm i

  build:
    commands:
      - echo "=== Build ==="
      - npm run build

  post_build:
    commands:
      - echo "=== Post-Build ==="
      - ls -al dist

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
