version: 0.2

env:
  exported-variables:
    - COMMIT_HASH

phases:
  pre_build:
    commands:
      - echo "=== Pre-Build ==="
      - export COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo "Resolved SHA (short): ${COMMIT_HASH}"

  install:
    commands:
      - echo "=== Install Dependencies ==="
      - cd frontend
      - npm install -g pnpm
      - pnpm install --frozen-lockfile

  build:
    commands:
      - echo "=== Build Project ==="
      - pnpm run build

  post_build:
    commands:
      - echo "=== Post-Build ==="
      - ls -al dist

artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
