version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm i
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls -al dist
artifacts:
  base-directory: frontend/dist
  files:
    - "**/*"
