services:
  api-blue:
    container_name: estime-api-blue
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - ./application/.env.prod
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /app/logs:/app/logs
    restart: unless-stopped

  api-green:
    container_name: estime-api-green
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - ./application/.env.prod
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /app/logs:/app/logs
    restart: unless-stopped

  alloy:
    image: grafana/alloy:v1.11.0
    container_name: alloy
    env_file:
      - ./application/.env.prod
    volumes:
      - ./alloy/config-prod.river:/etc/alloy/config-prod.river
      - /app/logs:/app/logs
      - alloy-data:/var/lib/alloy
    command: "run /etc/alloy/config-prod.river"
    restart: unless-stopped

volumes:
  alloy-data:
