services:
  api:
    container_name: estime-api
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - ./estime-api/.env.prod
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /app/logs:/app/logs

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    env_file:
      - ./estime-api/.env.prod
    volumes:
      - ./estime-api/alloy/config-prod.river:/etc/alloy/config-prod.river
      - /app/logs:/app/logs
      - alloy-data:/var/lib/alloy
    command: "run /etc/alloy/config-prod.river"
    restart: unless-stopped

volumes:
  alloy-data:
