services:
  api:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./app/logs/dev:/app/logs/dev

  mysql:
    ports:
      - "3306:3306"
