services:
  api-blue:
    container_name: estime-api-blue
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - ./application/.env.prod
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /app/logs:/app/logs
    restart: unless-stopped

  api-green:
    container_name: estime-api-green
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - ./application/.env.prod
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /app/logs:/app/logs
    restart: unless-stopped
