services:

  api:
    container_name: estime-api
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ./estime-api
      dockerfile: Dockerfile
    env_file:
      - ./estime-api/.env.local
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - app-logs:/app/logs

  mysql:
    ports:
      - "13306:3306"
    env_file:
      - ./estime-api/.env.local
    image: mysql:8.0
    container_name: estime-mysql
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    env_file:
      - ./estime-api/.env.local
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./estime-api/alloy/config.river:/etc/alloy/config.river
      - app-logs:/app/logs
      - alloy-data:/var/lib/alloy
    command: "run /etc/alloy/config.river"
    restart: unless-stopped

volumes:
  db_data:
  app-logs:
  alloy-data:
