services:
  mysql:
    image: mysql:8.0
    container_name: estime-mysql
    restart: unless-stopped
    env_file:
      - ./estime-api/.env.docker
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: estime-api
    depends_on:
      - mysql
    env_file:
      - ./estime-api/.env.docker
    volumes:
      - /app/logs:/app/logs

volumes:
  db_data:
