services:
  api:
    container_name: estime-api
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - ./estime-api/.env.dev
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - /app/logs:/app/logs
