services:
  api:
    container_name: estime-api
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - ./estime-api/.env.prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /app/logs:/app/logs
