spring:
  config:
    activate:
      on-profile: prod
    import:
      - application-common.yml
      - optional:file:.env.prod[.properties]

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  flyway:
    enabled: true

url:
  origin:
    client: ${URL_ORIGIN_CLIENT}

logging:
  discord:
    webhook-url: ${DISCORD_LOG_WEBHOOK_URL}

management:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: "EC2/estime-api/prod"
        region: ap-northeast-2
        url: ${CLOUDWATCH_URL}
