  scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: [ "localhost:9090" ]

    - job_name: "estime-api"
      scrape_interval: 15s
      metrics_path: '/actuator/prometheus'
      file_sd_configs:
        - files:
          - /etc/prometheus/targets.json
