spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:file:.env.local[.properties]

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 30000

  flyway:
    enabled: true

url:
  origin:
    client: ${URL_ORIGIN_CLIENT}

springdoc:
  swagger-ui:
    path: /docs

jdbc:
  datasource-proxy:
    query:
      enable-logging: true
      log-level: DEBUG
    slow-query:
      threshold: 1  # 초 단위
