ALTER TABLE room
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE participant
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE platform
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
