spring:
  config:
    activate:
      on-profile: local
    import:
      - application-common.yml
      - optional:file:estime-api/.env.local[.properties]

  datasource:
    hikari:
      register-mbeans: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /docs

management:
  endpoints:
    web:
      exposure:
        include: "prometheus, health"

  metrics:
    tags:
      application: "estime-api"
      environment: "local"
    distribution:
      percentiles-histogram:
        http.server.requests: true
