spring:
  config:
    activate:
      on-profile: dev
    import:
      - application-common.yml
      - optional:file:estime-api/.env.dev[.properties]

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  flyway:
    enabled: true

url:
  origin:
    client: ${URL_ORIGIN_CLIENT}

springdoc:
  swagger-ui:
    path: /docs

logging:
  discord:
    webhook-url: ${DISCORD_LOG_WEBHOOK_URL}

management:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: "EC2/estime-api/dev"
        region: ap-northeast-2
        url: ${CLOUDWATCH_URL}
