spring:
  config:
    activate:
      on-profile: prod
    import:
      - application-common.yml
      - optional:file:estime-api/.env.prod[.properties]

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  file:
    name: /app/logs/estime-api.log
  level:
    root: INFO
    com.estime: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n"

management:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: "EC2/estime-api/prod"
        region: ap-northeast-2
