spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /docs

server:
  forward-headers-strategy: framework

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

slack:
  bot:
    token: ${SLACK_BOT_TOKEN}

management:
  metrics:
    export:
      cloudwatch:
        enabled: false
