#logging:
#  level:
#    org.springframework.boot.context.config: DEBUG

spring:
  config:
    import: optional:file:.env.local[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

slack:
  bot:
    token: ${SLACK_BOT_TOKEN}
    channelId: ${SLACK_BOT_CHANNEL_ID}
    webhookUrl: ${SLACK_BOT_WEBHOOK_URL}

springdoc:
  swagger-ui:
    path: /docs
