name: CI Pipeline

on:
  pull_request:
    branches:
      [ be/dev ]
    types:
      [ opened, synchronize, reopened ]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpw
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: testpw

      URL_ORIGIN_LOCAL: ${{ secrets.URL_ORIGIN_LOCAL }}
      URL_ORIGIN_DEV: ${{ secrets.URL_ORIGIN_DEV }}
      URL_ORIGIN_PROD: ${{ secrets.URL_ORIGIN_PROD }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: JDK 21 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Gradle Wrapper 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 지정한 3개 환경 변수만 적용하여 YML 내용 확인
        run: |
          # envsubst 유틸리티 설치 (기본 이미지에 없을 경우)
          sudo apt-get update && sudo apt-get install -y gettext-base
          
          echo "==========================================================="
          echo "### [적용 후] application-common.yml (DB 정보만 치환) ###"
          echo "==========================================================="
          # 지정된 3개의 환경 변수만 실제 값으로 치환하여 출력
          cat src/main/resources/application-common.yml | envsubst '$SPRING_DATASOURCE_URL $SPRING_DATASOURCE_USERNAME $SPRING_DATASOURCE_PASSWORD'
          echo ""

      - name: 전체 빌드 및 테스트
        run: |
          echo "SPRING_PROFILES_ACTIVE = $SPRING_PROFILES_ACTIVE"
          echo "SPRING_DATASOURCE_URL = $SPRING_DATASOURCE_URL"
          ./gradlew clean build --stacktrace

      - name: Close PR, if build fail
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.TOKEN }}
          script: |
            const pull_number = ${{ github.event.pull_request.number }}
            const updated_title = `[BUILD FAIL] ${{ github.event.pull_request.title }}`
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              body: '빌드에 실패했습니다.',
              event: 'REQUEST_CHANGES'
            })
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              title: updated_title,
              state: 'closed'
            })
